-- *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
-- Remove views incorrectly created under the INTEGRATIONS schema
-- *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
DROP VIEW INTEGRATIONS.DIM_FACILITY ;
DROP VIEW INTEGRATIONS.DIM_PAD ;
DROP VIEW INTEGRATIONS.DIM_WELL_PAIR ;
DROP VIEW INTEGRATIONS.DIM_WELL ;
DROP VIEW INTEGRATIONS.DIM_STREAM ;
DROP VIEW INTEGRATIONS.DIM_TANK ;
DROP VIEW INTEGRATIONS.FACT_WELL_PRODUCTION ;
DROP VIEW INTEGRATIONS.FACT_WELL_INJECTION ;
DROP VIEW INTEGRATIONS.FACT_STREAM_DATA ;
DROP VIEW INTEGRATIONS.FACT_TANK_DATA ;

