CREATE SCHEMA BDA OWNED BY system;

CREATE COLUMN TABLE "BDA"."MASTER_XREF2" ("MASTER_TYPE" NVARCHAR(20) NOT NULL ,
	 "MASTER_KEY" INTEGER CS_INT NOT NULL ,
	 "SOURCE" NVARCHAR(20) NOT NULL ,
	 "SOURCE_VALUE" NVARCHAR(50) NOT NULL ,
	 "SOURCE_VALUE_INFO" NVARCHAR(100),
	 "SUSPECT" TINYINT CS_INT,
	 "CREATED" SECONDDATE CS_SECONDDATE NOT NULL ,
	 "CREATED_BY" NVARCHAR(100) NOT NULL ,
	 PRIMARY KEY ("MASTER_TYPE",
	 "SOURCE",
	 "SOURCE_VALUE")) UNLOAD PRIORITY 5 AUTO MERGE;